config/routes.rb
Rails.application.routes.draw do
resources :topics, only: [:index, :show]

  #resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :portos, except: [:show] do 
    put :sort, on: :collection 
  end

  get'portos/:id', to: 'portos#show', as: 'porto_show'
  
  get '/about-me', to: 'pages#about' 

  get '/contact', to: 'pages#contact'

  get '/news', to: 'pages#news'

  resources :blogs do 
  	member do 
  		get :toggle_status
  	end

  end

  mount ActionCable.server => '/cable'
  

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: {draft: 0, published: 1}
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title, :body

  	belongs_to :topic, optional: true

  	has_many :comments, dependent: :destroy

	 def self.special_blogs
	 	all
	 end

	 def self.featured_blogs 
	 	limit(2)
	 end

	 def self.recent
	 	order("created_at DESC")
	 end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:update, :create, :update, :destroy] 
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, admin: :all


  def index
  	if logged_in?(:admin)
    @blogs = Blog.recent.page(params[:page]).per(5)
	else 
	@blogs = Blog.published.recent.page(params[:page]).per(5)
	end 
    @page_title = "Developer Blog"
  end

  def show
  	if logged_in?(:admin) || @blog.published? #blog enum 
	    @blog = Blog.includes(:comments).friendly.find(params[:id])
	    @comment = Comment.new

	    @page_title = @blog.title
	    @seo_keywords = @blog.body
	else
		redirect_to blogs_path, notice: "You are not authorized to access this page"
	end 
			
	end



  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status 
      if @blog.draft? 
        @blog.published!
      elsif @blog.published?
        @blog.draft!
      end
          
      redirect_to blogs_url, notice: "Post has been updated."
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end
    
    def set_sidebar_topics
  	@side_bar_topics = Topic.with_blogs
  	end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def gravatar_helper user 
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
	end 

	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code,language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

		options = {
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_blocks: true,
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end 

	def blog_status_color blog 
		'color: red;' if  blog.draft?
	end

end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:admin) %>
<div class="breadcrumb blogcrumb" >
		<%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), class: "breadcrumb-item", style: blog_status_color(blog) %> 
		<%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog),class: "breadcrumb-item" %> 
		<%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "breadcrumb-item"  %> 	
<div>

<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
		<h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2> 
		<p class="blog-post-meta"> Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
		
		<div>
		<%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
        </div>

		<p><%= blog.body %></p>
		
</div>

app/views/blogs/_comment_form.html.erb
<% unless current_user.is_a? GuestUser %>
     <%= form_for @comment, url: '#' do |f|  %>

       <div class="form-group">
         <%= f.label :content %>
         <%= f.text_area :content, class: 'form-control' %>
       </div>

         <%= f.submit 'Post Comment', class: 'btn btn-primary' %>

     <%end%> 
   <% end %>

app/views/blogs/_comments.html.erb
<div class="comment-card">
   <div class="card-block">
     <div class="row">
       <div class= "col-md-1">

       </div>
       <div class="col-md-11">
           <%= comment.content %>    
       </div>
     </div>
   </div>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
      <% blog.errors.full_messages.each do |error| %>
        <%= alert_generator error %>
      <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :blog_title,  class: 'form-control', placeholder: 'Title' %>
  </div>

    <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
    			{ 
    				include_blank: true
    			},
    			class: 'form-control' 
				) 
	%>
  </div> 

  <div class="form-group"> 
	<%= form.radio_button :status, 'draft' %> 
	<%= form.label :status, 'Draft' %>
	<%= form.radio_button :status, 'published' %> 
	<%= form.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, id: :blog_body, class: 'form-control', rows: 15, placeholder: 'Content' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="row">
        <div class="col-md-8 blog-main">
         
           <h1>Editing Blog</h1>

			<%= render 'form', blog: @blog %>

			<%= link_to 'Show', @blog %> |
			<%= link_to 'Back', blogs_path %>

        
        </div><!-- /.blog-main -->
  
        <%= render 'shared/blog_sidebar' %>
    </div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>


    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h3 class="pb-3 mb-4 font-italic border-bottom">
            Dispatches from the Front 
          </h3>
              <%= render @blogs %>
              <%= paginate @blogs %>
        
        </div><!-- /.blog-main -->
  
        <%= render 'shared/blog_sidebar' %>
    </div>
</main>

app/views/blogs/new.html.erb
<div class="row">
        <div class="col-md-8 blog-main">
         
     <h1>New Blog</h1>

     <%= render 'form', blog: @blog %>

     <%= link_to 'Back', blogs_path %>

        </div><!-- /.blog-main -->
  
        <%= render 'shared/blog_sidebar' %>
    </div>

app/views/blogs/show.html.erb
<div class="row">
        <div class="col-md-8 blog-main">
         
           <div class="blog-post">
           	<strong> 
           		<h2 class="blog-post-title">
           			<%= @blog.title %>
           		</h2> 
           	</strong>

           	<p> <%= @blog.topic.title %> </p>
           	<p class="blog-post-meta"> Published <%= distance_of_time_in_words(@blog.created_at, Time.now) %> ago</p>

           	<nav aria-label="breadcrumb" class="breadcrumb">
           	    <%= link_to "Home", root_path, class: "breadcrumb-item" %> 
           	    <%= link_to "Blogs", blogs_path, class: "breadcrumb-item" %> <%= link_to @blog.topic.title, topic_path(@blog.topic.id), class: "breadcrumb-item" %> 
           	    <span class="breadcrumb-item active" aria-current="page">
           	    	<%= @blog.title %> </span>
           	 </nav>

           	 <div class="float-right">

           	 <%= render partial: 'blogs/admin_actions', locals: { blog: @blog } %>

           	</div>

           	<p><%= markdown(@blog.body) %></p>

           	<%= link_to fa_icon('back-left'), blogs_path %> 
          </div>

            <%= render "comments/comment_form" %>


          <div id="comments" data-blog-id="<%= @blog.id %>">
            <%= render @blog.comments %>
          </div>

        
        </div>
        <div>
        <%= render 'shared/blog_sidebar' %>
        </div>
</div>