config/routes.rb
Rails.application.routes.draw do
resources :topics, only: [:index, :show]

  #resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :portos, except: [:show] do 
    put :sort, on: :collection 
  end

  get'portos/:id', to: 'portos#show', as: 'porto_show'
  
  get '/about-me', to: 'pages#about' 

  get '/contact', to: 'pages#contact'

  get '/news', to: 'pages#news'

  resources :blogs do 
  	member do 
  		get :toggle_status
  	end

  end

  mount ActionCable.server => '/cable'
  

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/porto.rb
class Porto < ApplicationRecord
	validates_presence_of :title, :body
	
	has_many :technologies, dependent: :destroy
	accepts_nested_attributes_for :technologies, 
								allow_destroy: true,
								reject_if: lambda { |attrs| attrs['name'].blank? }

	include Placeholder 

	mount_uploader :thumb_image, PortfolioUploader 
	mount_uploader :main_image, PortfolioUploader 

	def self.angular
		where(subtitle: 'Angular')
	end

	def self.by_position 
		order("position ASC")
	end

	scope :ruby_on_rails_porto, -> { where(subtitle: 'Ruby on Rails') }

	def self.by_position 
		order("position ASC")
	end


end

app/controllers/portos_controller.rb
class PortosController < ApplicationController
	before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
	
	layout "portfolio"
	access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :sort]}, admin: :all
	
	def index
		@portfolio_items = Porto.by_position
	end

	def sort
	params[:order].each do |key, value|
      	Portos.find(value[:id]).update(position: value[:position])
      end
    end

	def angular
		@portfolio_items = Porto.angular
	end

	def sort
		params[:order].each do |key, value|
			Porto.find(value[:id]).update(position: value[:position])
		end 
		render nothing: true
	end

	def new 
		
		@portfolio_item = Porto.new
		 @portfolio_item.technologies.build 
	end

	def create 
		@portfolio_item = Porto.new(porto_params)

	    respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portos_path, notice: 'Portfolio Item was successfully created.' }
	      else
	        format.html { render :new }
	      end
	    end
	end

	def edit
		times do @portfolio_item.technologies.build end 
	end

	def update

		respond_to do |format|
	      if @portfolio_item.update(porto_params)
	        format.html { redirect_to porto_path(@portfolio_item.id), notice: 'Portfolio Item was successfully updated.' }
	      else
	        format.html { render :edit }
	      end
	    end
	end

	def show
		#binding.pry
	end

	def destroy 

		@portfolio_item.destroy

		respond_to do |format| 
			format.html { redirect_to portos_url, notice: "Portfolio item was removed"}
		end
	end
	private 
		def porto_params 
		params.require(:porto).permit(
									:title, 
									:subtitle, 
									:body, 
									:main_image,
									:thumb_image,
									technologies_attributes: [:id, :name, :_destroy]
									)
		end

		def set_portfolio_item 
			@portfolio_item = Porto.find(params[:id])
		end

end

app/helpers/portos_helper.rb
module PortosHelper
	def image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end

	def portfolio_img img, type 
		if img.model.main_image? || img.model.thumb_image?
			img 
		elsif type == 'thumb'
			image_generator(height: '350', width: '200')
		else
			image_generator(height: '600', width: '400')
		end
	end
		#self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
		#self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
end

app/views/portos/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
		<% if portfolio_item.errors.any? %>
    	 	<% portfolio_item.errors.full_messages.each do |error| %>
        		<%= alert_generator error %>
      		<% end %>
  		<% end %>
	
		  <div class="form-group">
		    <%= form.label :title %>
		    <%= form.text_field :title, id: :blog_title , class: 'form-control'%>
		  </div>

		  <div class="form-group">
		    <%= form.label :subtitle %>
		    <%= form.text_field :subtitle, id: :blog_title, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		    <%= form.label :body %>
		    <%= form.text_area :body, id: :blog_body, class: 'form-control' %>
		  </div>

		  <div class="form-group">
		  	<label class="btn btn-primary btn-block">
		  		Upload main image file <%= form.file_field :main_image, style: 'display:none;' %>
		  	</label>
		  </div>

		  <div class="form-group">
		  	<label class="btn btn-primary btn-block">
		  		Upload thumb image file <%= form.file_field :thumb_image, style: 'display:none;' %>
		  	</label>
		  </div>

		 <div class="col-md-6">
		  	<%= form.fields_for :technologies do |tech_form| %>
		  		<%= render 'technology_fields', f: tech_form %>
		  		<% end %>
		  </div>
		  	
		  	<div class= "col-md-6">
		  		<%= link_to_add_association "Add Technology", form, :technologies, class: "btn btn-success btn-block" %>
		  	</div>
		 	<hr>

		  <div class="actions">
		    <%= form.submit "submit", class: 'btn btn-primary btn-block' %>
		  </div>
<% end %>

app/views/portos/_portfolio_item.html.erb
	<div class="col-md-4">
        <div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
				  
          <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>

                <div class="card-body" >
                  <p class="card-text">
                  	<span>
                  		<strong>
                  			<%= link_to portfolio_item.title, porto_path(portfolio_item.id) %>
                  			
                  		</strong>
                  	</span>
                  	<span><em>
                  		<%= portfolio_item.subtitle %>
                  	</em></span>
						
					</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">

                      <%= link_to "View", porto_path(portfolio_item.id), class: "btn btn-sm btn-outline-secondary" %>
                      
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>

app/views/portos/_technology_fields.html.erb
<div class="form-group nested-fields">
	<%= f.label :name %> 
	<%= f.text_field :name, class: 'form-control' %> 
	<%= link_to_remove_association 'Remove Technology', f, class: "btn btn-danger" %> 
</div>

app/views/portos/angular.html.erb
<h1> Portfolio Items </h1>

<%= link_to "Create New Portfolio Item", new_porto_path if logged_in?(:admin)%>

<p> <%= new_porto_path %> </p>
<p> <%= new_porto_url %> </p>

<% @portfolio_items.each do |item| %>

	<p><%= link_to item.title, porto_path(item.id) %> </p>  
	<h3><%= item.subtitle %></h3>
	<p><%= item.body %></p>
	<% unless item.thumb_image.nil? %>
		<img src=<%= item.thumb_image %> alt="image for #{item}" width="150px" height="200px"/>
	
	<%end%>
	<br/>
	<%= link_to "Edit", edit_porto_path(item.id)if logged_in?(:admin) %>
	<%= link_to "Delete", porto_path(item.id), method: :delete, data: { confirm: 'Delete Portfolio Item?'} if logged_in?(:admin)%>
	
<% end %>

app/views/portos/edit.html.erb
<div class="container">
	<h1> Edit Portfolio Item </h1>
	 
	 <%= render 'form', porfolio_items: @porfolio_item %>
</div>

app/views/portos/index.html.erb
<div class="album py-5 bg-light">
	<div class="container">
		<h1> Portfolio Items </h1>
		<hr>
  		<div class="row <%= "sortable" if logged_in?(:admin) %>">
			
			<%= render partial: 'portfolio_item', collection: @portfolio_items %>
 
		</div>
	</div>
</div>
	<%= link_to "Create New Portfolio Item", new_porto_path if logged_in?(:admin) %>

app/views/portos/new.html.erb
<div class="container">
	<h1> Create a new Portfolio Item </h1>
 
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portos/show.html.erb
<div class="container porto-container" />
	<div class="row">
		<div class="col-md-7">

			<%= image_tag portfolio_img(@portfolio_item.main_image, 'main') %>
			
		</div>
		<div class="col-md-5">
	
			<h1><%= @portfolio_item.title %> </h1>
			<h2><%= @portfolio_item.subtitle %> </h2>
	
			<p><%= @portfolio_item.body %> </p>

			<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %> </p>
				<%end %>

			<% if logged_in?(:admin) %>
				<p>
					<%= link_to "Edit", edit_porto_path(@portfolio_item.id), class: "btn btn-primary" %> 
					<%= link_to "Delete", porto_path, method: :delete, data: { confirm: 'Delete Portfolio Item?'}, class: "btn btn-warning"%>	
				</p>
				
			<% end %>

		</div>
		<hr>
	
	</div>
</div>