config/routes.rb
Rails.application.routes.draw do
resources :topics, only: [:index, :show]

  #resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :portos, except: [:show] do 
    put :sort, on: :collection 
  end

  get'portos/:id', to: 'portos#show', as: 'porto_show'
  
  get '/about-me', to: 'pages#about' 

  get '/contact', to: 'pages#contact'

  get '/news', to: 'pages#news'

  resources :blogs do 
  	member do 
  		get :toggle_status
  	end

  end

  mount ActionCable.server => '/cable'
  

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
	<div class="inner">
	        <%= source_helper("application") %>
	        <%= copyright_generator %>   
	</div>
</footer>

app/views/shared/_application_nav.html.erb
  <div class="inner">
          <h3 class="masthead-brand">Hugh Harker</h3>
           <nav class="nav nav-masthead justify-content-center">
            <%= nav_helper 'nav-link', 'span class="app-nav"' %>
            <%= login_helper("nav-link app-nav")%>
          </nav>
        </div>

app/views/shared/_blog_footer.html.erb
 <footer class="blog-footer">
	<%= copyright_generator %>   
	
	<p>
		<a href="#">Back to top</a>
	</p>
</footer>

app/views/shared/_blog_header.html.erb
 <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="#">Large</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
          </div>
        </div>
      </header>

app/views/shared/_blog_masthead.html.erb
 <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
          	<span>
              <%= link_to 'New Blog', new_blog_path, class: 'text-muted' if logged_in?(:admin) %>
          </span>
          <span> 
          	<%= link_to 'Topics', topics_path %>
          </span>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="#">Large</a>
          </div>

          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
          </div>
        </div>
      </header>

app/views/shared/_blog_nav.html.erb
 

 <nav class="navbar avbar-expand-lg navbar-dark bg-primary">
 	<a class="navbar-brand" href="#">Hugh Harker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    	<%= nav_helper 'nav-link', 'li' %>
    	<%= login_helper 'nav-link' %>
    </ul>
  </div>
</nav>

</nav>

app/views/shared/_blog_sidebar.html.erb
        <aside class="col-md-4 blog-sidebar">
          <div class="p-3 mb-3 bg-light rounded">
            <h4 class="font-italic">About</h4>
            <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
         	<%= source_helper("alert alert-info blog-sidebar-source")%>

          <div class="sidebar-module">
          	<h4> Topics </h4>
          	<%  @side_bar_topics.each do |topic| %>
          	   <p><%= link_to topic.title, topic_path(topic) %> </p>
          	<% end %>

          </div>

          <div class="p-3">
            <h4 class="font-italic">Elsewhere</h4>
            <ol class="list-unstyled social-links">
              
              <li><a href="https://github.com/htharker42"><%= fa_icon "github-square" %>
                    </a>
              </li>

              <li><a href="https://twitter.com/htharker"><%= fa_icon "twitter-square" %>
               </a></li>


              <li><a href="https://twitter.com/htharker"><%= fa_icon "instagram-square" %>
               </a></li>

            </ol>
          </div>
        </aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
  <div class=<%= location %> >
      <div> <%= link_to "Home", root_path %> </div>
      <div> <%= link_to "About Me", about_me_path %> </div>
      <div> <%= link_to "Blog", blogs_path %> </div>
      <div> <%= link_to "Portfolio", portos_path %> </div>
      <div> <%= link_to "Contact", contact_path %> </div>
  </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
      <div class="container">
        <p class="float-right">
         	<%= link_to 'View all Portfolio Items', portos_path %> | 
         	 <a href="#">Back to top</a>
        </p>
        	<hr>
         <%= source_helper("portfolio") %>
       	<%= copyright_generator %>

      </div>
    </footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Portfolio</h1>
      <p class="lead text-muted">The collection below includes projects in both the computer programming/development and urban planning + design fields. As a design professional, it is fundimental to combine an understanding of contextual data and the user experience to produce a positive outcome. It is this understanding that I attempt to bring to all my projects.</p>
      <p>
        <%= link_to 'About me', about_me_path, class: "btn btn-primary my-2"%>
        <%= link_to 'Blog', blogs_path, class: "btn btn-secondary my-2" %>
      </p>
    </div>
 </section>

app/views/shared/_portfolio_nav.html.erb
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">The projects in the portfolio are broken into two type: Programming and Urban Planning and Design.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Explore</h4>
              <ul class="list-unstyled">
                <%= nav_helper 'text-white', 'li' %>
                <li><%= login_helper 'text-white' %></li>
                <li><a href="https://twitter.com/htharker" class="text-white">Follow on Twitter</a></li>
                <li><a href="mailto: htharker@gmail.com" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <strong>Hugh Harker</strong>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    